baseURL = "https://kshlug.github.io/"
languageCode = "en-us"
title = " کرمانشاه لاگ"
theme = "minimal"
disqusShortname = "kshlug-ir" # delete this to disable disqus comments
shamsiDateFormat = "d MMMماه yyyy"


[params]
    author = "کرمانشاه‌لاگ"
    description = "به کرمانشاه لاگ خوش آمدید :) لاگ به معنی گروه کاربران گنو/لینوکس است و از افراد مختلف که به منظور تبادل اطلاعات در حوزه‌ی نرم‌افزارهای آزاد و متن‌باز دور هم جمع می‌شوند، تشکیل شده است. اگر تمایل دارید دانش خود را با دیگران به اشتراک بگذارید یا کنجکاوید تا از تکنولوژی‌های آزاد جدید اطلاعاتی کسب کنید و یا از بودن در کنار چند دوست فعال در این زمینه لذت می‌برید، با ما همراه شوید. در ضمن، شرکت در جلسات برای عموم آزاد و رایگان است. "
    githubUsername = "kshlug"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Vazir"#"Raleway" #vazir  # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "c++", "c", "python", "ruby"]
    address = "آدرس: بلوار شهید بهشتی، موسسه آموزشی جهاد دانشگاهی"
    telegram= "tiny.cc/Kermanshah"
    author_link = "kshlug"
    
[[menu.main]]
    url = "/"
    name = "خانه"
    weight = 7

[[menu.main]]
    url = "/session/"
    name = "جلسه‌های لاگ"
    weight = 6

[[menu.main]]
    url = "/about/"
    name = "درباره ما"
    weight = 5

[[menu.main]]
    url = "/new/"
    name = "اخبار"
    weight = 4

[[menu.main]]
    url = "/event/"
    name = "رویداد ها"
    weight = 3

[[menu.main]]
    url = "/post/"
    name = "پست های آزاد"
    weight = 2

[[menu.main]]
    url = "https://lugs.ir"
    name = "لاگ‌های دیگر"
    weight = 1


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
[[menu.icon]]
    url = "https://www.openstreetmap.org/#map=18/34.33387/47.08716"
    name = "map-marker"
    weight = 7

[[menu.icon]]
    url = "https://tiny.cc/Kermanshah"
    name = "telegram"
    weight = 5

[[menu.icon]]
    url = "https://github.com/kshlug/"
    name = "github"
    weight = 2


[[menu.icon]]
    url = "https://www.instagram.com/kshlug.ir/"
    name = "instagram"
    weight = 4


[[menu.icon]]
    url = "https://twitter.com/kshlug"
    name = "twitter"
    weight = 3



[[menu.icon]]
    url = "https://www.facebook.com/kshlug.ir/"
    name = "facebook"
    weight = 9

[[menu.icon]]
    url = "https://gitlab.com/kshlug"
    name = "gitlab"
    weight = 1
